require('dotenv').config()
const express = require('express')
const path = require('path')
const cookieParser = require('cookie-parser')
const connectDB = require('./config/db')
const app = express()
const authRoutes = require('./routes/authRoutes')
const protectedRoutes = require('./routes/protectedRoutes')
const todoRoutes = require('./routes/todoRoutes')

connectDB()
app.use(express.json())
app.use(express.static(path.join(__dirname, 'public')))
app.use(cookieParser())
app.use('/api/auth', authRoutes)
app.use('/api/protected', protectedRoutes)
app.use('/api/todo', todoRoutes)
app.listen(3000, () => {
  console.log('Server running on port 3000')
})
